Added fragment block
hlxsites/bevespi pull request #23
Opened 2023-10-10 12:39 UTC by lansami

Fix #20 

Test URLs:
- Before: https://main--bevespi--hlxsites.hlx.page/
- After: https://issue-20-home-styling--bevespi--hlxsites.hlx.page/

2023-10-13 15:45 UTC, paolomoz requested changes
@lansami it seems that styling is not done yet. I would suggest to complete before review
see screenshot in comments

2023-10-13 15:45 UTC, paolomoz commented
<img width="1426" alt="Screenshot 2023-10-13 at 17 43 14" src="https://github.com/hlxsites/bevespi/assets/111385/447bfbc4-776f-476e-b36d-408ecece38c4">

2023-10-16 08:57 UTC, paolomoz commented
@lansami I think it needs some styling adjustments, see screenshot:

<img width="1365" alt="Screenshot 2023-10-16 at 10 56 13" src="https://github.com/hlxsites/bevespi/assets/111385/4757c576-3016-4e45-a0a4-4fc81f6481df">

2023-10-16 13:59 UTC, paolomoz commented
There are some style fix required, see screenshot below:

- Resources and support has a different font face
- pink icon is missing (I see you noted it is known, but I would prefer to include pictures in this PR; any reason to not include them?)
- Explore the services.. text; should not be upper case, and should be 16px not 17px
- Based on what we decided for the project, font size is in rem with font root size 10px and everything else (padding, margin, etc..) is px
- Padding top bottom. should be increased a bit

<img width="1436" alt="Screenshot 2023-10-16 at 15 54 57" src="https://github.com/hlxsites/bevespi/assets/111385/01485455-63d9-4e49-82f4-57081bc48628">

2023-10-16 14:09 UTC, paolomoz commented
Style fixes for the fragment part:

- Orange title font size should be 18px not 22px, 14px for mobile
- text font size should be 15px not 16px, 13px for mobile
- collapsed fragment font size should be 15px not 9px
- fragment should expand as soon as its title get above the fold, not later
- scroll when clicking on the + should be slower
- we changed max-width to 1200px for header, footer and content (fragment still at 1002px)
- after scrolling on mobile the title should be close to the to of the window (there is some padding now)
- ul should not have padding left
- bold text is not rendered

<img width="1430" alt="Screenshot 2023-10-16 at 16 00 45" src="https://github.com/hlxsites/bevespi/assets/111385/79d46278-2c42-440e-aacb-dd1f463612a8">

2023-10-18 07:00 UTC, paolomoz approved these changes
@lansami approved with comments

2023-10-18 07:35 UTC, lansami commented on blocks/fragment/fragment.css
> +    left: 46%;
I've updated the styling to be more specific to the "Important Safety Information" fragment

2023-10-18 07:35 UTC, lansami commented on blocks/fragment/fragment.css
> +}
updated to be more specific to the "Important Safety Information"

2023-10-18 08:54 UTC, merged